blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


# Create your models here.
class Blog(models.Model):
    title_post = models.CharField(max_length=50, verbose_name='Заголовок статьи')
    content_post = models.CharField(max_length=3500, verbose_name='Содержание статьи')
    image_post = models.ImageField(upload_to='preview', verbose_name='Изображение', null=True, blank=True)
    data_post = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    # признак публикации,
    publ_on_off = models.BooleanField(default=True, verbose_name='Опубликовано')
    # количество просмотров.
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    slug = models.CharField(max_length=50, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return f'{self.title_post} {self.image_post} {self.data_post}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models import Blog
from main.send_mailing import sent_mail


# Create your views here.
class BlogCreateView(CreateView):
    model = Blog
    fields = ('title_post', 'content_post', 'image_post', 'publ_on_off')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title_post)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title_post', 'content_post', 'image_post', 'publ_on_off')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title_post)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publ_on_off=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{%  block content %}
    <div class="row">
        <div class="6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить статью?</p>
                        <button type="submit" class="btn btn-success">
                            Удалить!
                        </button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}

{% block content%}

    <div class="container">
        <div class="row">
            <!-- Левая часть с изображением -->
            <div class="col-md-4">
                <img src="/media/{{ object.image_post }}" alt="Изображение товара" class="img-fluid">
            </div>

            <!-- Правая часть с информацией о товаре -->
            <div class="col-md-8">
                <h2>Название статьи: {{ object.title_post }} </h2>
                <p>slug: {{ object.slug }}</p>
                <p><b>Дата создания:</b> {{ object.data_post }} <b>Количество просмотров:</b> {{ object.views_count }}</p>
                <p>Содержание статьи: {{ object.content_post }}</p>

            </div>


        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{%  block content %}
    <div class="row">
        <div class="6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Изменить
                            {% else %}
                                Создать статью
                            {% endif %}

                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}

    {% block content%}
    <div class="row text-center">

        <div>
            <h1>Блог Мехмета - ифенди</h1>
            <a href="/blog/create" class="btn btn-primary">Создать статью</a>
        </div>

    {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <div class="card-body" >
                        <h3 class="card-title">{{ object.title_post }}</h3>
                        <img src="/media/{{ object.image_post }}" alt="Card image" class="card-image">

                    </div>
                    <div class="card p-3">
                        <a href="{% url 'blog:view' object.pk %}" class="btn btn-primary">Читать</a>
                        {% if user.is_authenticated %}
                        <a href="{% url 'blog:edit' object.pk %}" class="btn btn-secondary">Изменить</a>
                        <a href="{% url 'blog:delete' object.pk %}" class="btn btn-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:"4" and not forloop.last %}
            </div>
    <div class="row text-center">
        {% endif %}
    {% endfor %}
    </div>
    {% endblock %}