blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password
app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=11, verbose_name='телефон', null=True, blank=True)
    avatar = models.ImageField(upload_to='users', verbose_name='аватар', null=True, blank=True)

    name_client = models.CharField(max_length=20, verbose_name='Имя клиента')
    first_name_client = models.CharField(max_length=20, verbose_name='Фамилия клиента', null=True, blank=True)

    user_active = models.BooleanField(default=False, verbose_name='Авторизация')
    key_active = models.CharField(max_length=6, default=None, verbose_name='код авторизации', null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
import random

from main.models import Client
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        new_user = form.save()
        activ_pass = ''.join(str(random.randint(0, 9)) for _ in range(6))

        # Запишите сгенерированный код в поле key_active модели User
        new_user.key_active = activ_pass
        new_user.save()

        send_mail(
            subject='Вы зарегестрировались на сервисе',
            message=f'Нужно срочно пройти авторизацию Ваш код {activ_pass}'
                    f'\nВаш код {activ_pass}, введите в личном кабинете',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


class ProfileView(UpdateView, LoginRequiredMixin):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        kod_active_true = request.POST.get('kod_active')
        print(kod_active_true)
        print(request.user.key_active)
        if request.user.key_active == kod_active_true:
            # Если введенный код совпадает с key_active пользователя,
            # активируем пользователя
            request.user.user_active = True
            request.user.save()

            return redirect('users:profile')

        else:
            return redirect('users:profile')


    # def kod_active(request):
    #     if request.method == 'POST':
    #         kod_active_true = request.POST.get('kod_active')
    #         print(kod_active_true)
    #
    #         if request.user.key_active == kod_active_true:
    #             # Если введенный код совпадает с key_active пользователя,
    #             # активируем пользователя и удаляем код
    #             request.user.user_active = True
    #             request.user.key_active = None  # Опционально, чтобы удалить код после активации
    #             request.user.save()
    #
    #             return redirect('users:login')


def generate_new_password(request):
    new_password = ''.join(str(random.randint(0, 9)) for _ in range(6))
    send_mail(
        subject='Изменение пароля',
        message=f'Ваш новый пароль {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse_lazy('users:login'))


# def kod_active(request):
#     if request.method == 'POST':
#         kod_active_true = request.POST.get('kod_active')
#         print(kod_active_true)
#
#         if request.user.key_active == kod_active_true:
#             # Если введенный код совпадает с key_active пользователя,
#             # активируем пользователя и удаляем код
#             request.user.user_active = True
#             request.user.key_active = None  # Опционально, чтобы удалить код после активации
#             request.user.save()
#
#             return redirect('users:login')

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content%}

    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    Выполнить вход
                </div>

            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </form>
            </div>
        </div>

        </div>

    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content%}

    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    Регистрация
                </div>

            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
        </div>

        </div>

    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content%}
<div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <div class="card-body" >
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    Профайл
                </div>


{% if user.is_staff == True %}
                <div>Вам не нужно авторизоваться - вы админ</div>
{% else %}
                {% if user.user_active == False %}
              <div>Пройдите авторизацию</div>




    <div>
       <form method="post" action="" class="form-floating">
      {% csrf_token %}
       <input type="text" name="kod_active" placeholder="Введите код из почты">
       <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Авторизоваться</button>
       </form>
    </div>

                {% else %}
                <h3>Вы авторизованы</h3>
                {% endif %}
{% endif %}




            </div>
            <div class="image-container">
                <img src="/media/{{ object.avatar }}" alt="Card image" class="card-image">
            </div>

            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
        </div>
            <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Новый пароль</a>
            </div>

        </div>
    </div>

    </div>

</div>


{% endblock %}