blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.views.decorators.cache import cache_page

from . import views
from .models import Mailing
from .views import MailingListView, MailingCreateView, MailingDeleteView, \
    MailingUpdateView, ClientListView, ClientDeleteView, ClientUpdateView, ClientCreateView, MailingLogListView

# from main.views import

urlpatterns = [
    path('', MailingListView.as_view(), name='index'),
    path('mailinglogs/', MailingLogListView.as_view(), name='логи'),

    path('create/', MailingCreateView.as_view(), name='create_mailing'),
    path('update/<int:pk>', MailingUpdateView.as_view(), name='update_mailing'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='delete'),

    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('client_update/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('client/', ClientListView.as_view(), name='client')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password
app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
]

blog/models.py
from django.db import models


# Create your models here.
class Blog(models.Model):
    title_post = models.CharField(max_length=50, verbose_name='Заголовок статьи')
    content_post = models.CharField(max_length=3500, verbose_name='Содержание статьи')
    image_post = models.ImageField(upload_to='preview', verbose_name='Изображение', null=True, blank=True)
    data_post = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    # признак публикации,
    publ_on_off = models.BooleanField(default=True, verbose_name='Опубликовано')
    # количество просмотров.
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    slug = models.CharField(max_length=50, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return f'{self.title_post} {self.image_post} {self.data_post}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

main/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Модель клиента для рассылки"""
    mail_client = models.CharField(max_length=25, verbose_name='Почта клиента')
    name_client = models.CharField(max_length=20, verbose_name='Имя клиента')
    first_name_client = models.CharField(max_length=20, verbose_name='Фамилия клиента', null=True, blank=True)
    last_name_client = models.CharField(max_length=20, verbose_name='Отчество клиента', null=True, blank=True)

    client_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец',
                                     **NULLABLE)

    def __str__(self):
        return f"Клиент: Ф-{self.name_client} И-{self.first_name_client} О-{self.last_name_client}.Письмо отправляем на {self.mail_client}"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


# Create your models here.
class Mailing(models.Model):
    """Модель рассылки, время, периодичность, статус"""
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'
    STATUSES = (
        (STATUS_STARTED, 'Запущена'),
        (STATUS_CREATED, 'Создана'),
        (STATUS_DONE, 'Завершена'),
    )

    send_time = models.TimeField(auto_now_add=False, default='Время в формате Ч:М', verbose_name='Время рассылки')
    frequency = models.CharField(max_length=20, choices=PERIODS, verbose_name='Периодичность рассылки')
    status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_CREATED, verbose_name='Статус рассылки')

    name_mailing = models.CharField(max_length=15, verbose_name='Название рассылки')
    theme_mess = models.CharField(max_length=200, verbose_name='Тема письма')
    body_mess = models.TextField(verbose_name='Тело письма')

    # Зависимость от владельца продукта
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)

    client = models.ManyToManyField(Client)

    def __str__(self):
        return (f"Рассылка #{self.pk}. Время отправки- {self.send_time} "
                f"Периодичность- {self.frequency}. Статутс {self.status}"
                f"Название рассылки - {self.name_mailing}")

    class Meta:
        verbose_name_plural = "Рассылки"


class MailingLog(models.Model):
    """Модель логов рассылки"""

    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    log_status = models.CharField(max_length=20, choices=STATUSES, verbose_name='статус попытки')
    log_client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='подписчик')
    log_mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    response = models.TextField(**NULLABLE, verbose_name='ответ сервера')

    def __str__(self):
        return f"{self.log_client} - {self.log_mailing} ({self.log_status}) в {self.created_time}"

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

main/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from pytils.translit import slugify
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from blog.models import Blog
from main.models import Client, Mailing, MailingLog


# Create your views here.
class MailingListView(ListView):
    """Показывает все рассылки"""
    model = Mailing
    template_name = 'main/index.html'
    context_object_name = 'object'

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if user.groups.filter(name='manager').exists() or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                owner=user.pk
            )

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_count = Mailing.objects.count()
        context['mailing_count'] = mailing_count

        active_mailings = Mailing.objects.filter(status='created').count()
        context['active_mailings'] = active_mailings

        unique_clients = Client.objects.count()
        context['unique_clients'] = unique_clients

        blogs = Blog.objects.filter(publ_on_off=True)
        all_post = list(blogs)
        if len(all_post) >= 3:
            blog_list = sample(list(blogs), 3)
            context['blog_list'] = blog_list

        else:
            blog_list = all_post
            context['blog_list'] = blog_list

        return context


class MailingCreateView(CreateView, LoginRequiredMixin):
    """Класс для создания рассылки"""
    model = Mailing
    fields = ('name_mailing', 'theme_mess', 'body_mess', 'frequency', 'send_time')
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name_mailing)
            new_mat.save()

        return super().form_valid(form)


class MailingDeleteView(DeleteView, LoginRequiredMixin):
    """Класс для удаления рассылки"""
    model = Mailing
    success_url = reverse_lazy('index')


class MailingUpdateView(UpdateView, LoginRequiredMixin):
    """Класс для изменения рассылки"""
    model = Mailing
    fields = ('status', 'name_mailing', 'theme_mess', 'body_mess', 'frequency', 'send_time', 'client')
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name_mailing)
            new_mat.save()

        return super().form_valid(form)


class ClientListView(ListView, LoginRequiredMixin):
    """Вывод всех клиентов на странице"""
    model = Client
    template_name = 'main/client.html'

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                client_owner=user.pk
            )
        return queryset


class ClientDeleteView(DeleteView, LoginRequiredMixin):
    """Класс удаления клиентов для рассылок"""
    model = Client
    success_url = reverse_lazy('client')

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if user.groups.filter(name='manager').exists() or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                mailing_owner=user.pk
            )
        return queryset


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    """Класс изменения клиентов для рассылок"""
    model = Client
    fields = ('mail_client', 'name_client', 'first_name_client', 'last_name_client')
    success_url = reverse_lazy('client')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.mail_client)
            new_mat.save()

        return super().form_valid(form)


class ClientCreateView(CreateView, LoginRequiredMixin):
    """Класс создания клиентов для рассылок"""
    model = Client
    fields = ('mail_client', 'name_client', 'first_name_client', 'last_name_client')
    success_url = reverse_lazy('client')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.mail_client)
            new_mat.save()

        return super().form_valid(form)


class MailingLogListView(ListView):
    """Показывает все логи"""
    model = MailingLog
    template_name = 'main/mailinglogs.html'
    context_object_name = 'object'

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                log_mailing=user.pk
            )
        return queryset

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="canonical" href="https://bootstrap-4.ru/docs/5.3/examples/headers/">
	<!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

	<!-- Favicons -->
	<meta name="theme-color" content="#712cf9">

   <style>
   .card-image {
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
}


      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

</head>
<body>

<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="/" class="nav-link px-2 text-white">Главная</a></li>
          <li><a href="/client/" class="nav-link px-2 text-white">Клиенты</a></li>
          <li><a href="/blog/" class="nav-link px-2 text-white">Блог</a></li>
            {% if user.is_authenticated %}
          <li><a href="/mailinglogs/" class="nav-link px-2 text-secondary">Логи</a></li>
            {% endif %}
        </ul>

        <div class="text-end">
            {% if user.is_authenticated %}
            <a class="p-2 btn btn-danger" href="{% url 'users:logout' %}">Выйти</a>
            <a class="p-2 btn btn-warning" href="{% url 'users:profile' %}">Профиль</a>
        {% else %}
            <a class="btn btn-outline-light me-2" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-warning" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}

        </div>
      </div>
    </div>
  </header>


{% block content%}



{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/client.html
{% extends 'main/base.html' %}
{% block content%}

<div>
    <div class="col-12 p-3 border bg-light">
        <div class="card mb-4 box-shadow">
            <div class="card">
                <div class="card-body" >
    {% if user.is_authenticated %}
        <a href="/create_client" class="btn btn-primary col-12 row text-center">Добавить клиента для рассылки</a>

                </div>
            </div>
        </div>
    </div>
</div>

{% for object in object_list %}
<div class="row align-item-start p-3 border bg-light"">
    <div class="col">
        <div class="col-12 card-body">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <div class="card-body" >
                        <h4 class="card-title">Клиент №{{ object.pk }}</h4>
                        <div>Имя клиента {{ object.name_client }},
                            Фамилия клиента- {{ object.first_name_client }},
                            Отчество клиента - {{ object.last_name_client }}
                            Почта клиента - {{ object.mail_client }}</div>

                        <a href="{% url 'delete_client' object.pk %}" class="btn btn-danger">Удалить</a>
                        <a href="{% url 'update_client' object.pk %}" class="btn btn-info">Изменить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% else %}
        <h6>Зарегестрируйтесь или войдите, чтобы управлять клиентами для рассылки</h6>
{% endif %}
{% endblock %}

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}

{%  block content %}
    <div class="row">
        <div class="6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить клиента?</p>
                        <button type="submit" class="btn btn-success">
                            Удалить!
                        </button>
                        <a href="{% url 'index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}
{% block content%}


    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Добавляем клиента</h1>
            </div>
        </div>
    </div>
{% if user.is_authenticated %}
 <div class="card-body">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">
            {% if object %}
                Изменить клиента
            {% else %}
                Создать клиента
            {% endif %}

        </button>
    </form>
</div>

{% endif %}
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content%}


<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h1 class="text-center">Здесь начинается магия</h1>
        </div>
    </div>
</div>

<div>
    <div class="col-12 p-3 border bg-light">
        <div class="card mb-4 box-shadow">
            <div class="card">
                <div class="card-body" >
    {% if user.is_authenticated %}
        <a href="/create" class="btn btn-primary col-12 row text-center">Создать рассылку</a>

                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="col-12 p-3 border bg-light">
        <div class="card mb-4 box-shadow">
            <div class="card">
                <div class="card-body" >
   <div>
    <div class="col-12 p-3 border bg-light">
        <div class="card mb-4 box-shadow">
            <div class="card">
                <div class="card-body" >
  <div>Рассылок {{ object.mailing_count }} :
      Активные рассылки {{ object.active_mailings }} :
        Клиентов для рассылок {{ object.unique_clients }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
                </div>
            </div>
        </div>
    </div>
</div>


{% for object in object_list %}
<div class="row align-item-start p-3 border bg-light">
    <div class="col">
        <div class="col-12 card-body">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <div class="card-body" >
                        <h4 class="card-title">Рассылка №{{ object.pk }}</h4>
                        <div>Время отправки {{ object.send_time }},
                            Частота отправки - {{ object.frequency }}, статус рассылки - <b>{{ object.status }}</b></div>
                        <a href="{% url 'delete' object.pk %}" class="btn btn-danger">Удалить</a>
                        <a href="{% url 'update_mailing' object.pk %}" class="btn btn-info">Изменить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card">
                <div class="card-body" >
                    <h4 class="card-title">Что отправляем</h4>
                    <div>Тема письма {{ object.theme_mess }}</div>
                    <div>Текст письма - {{ object.body_mess }}</div>

                    <a href="/client/" class="btn btn-primary">Посмотреть список клиентов</a>

                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% else %}
        <h6>Зарегестрируйтесь или войдите, чтобы создать рассылку</h6>
    {% endif %}
<div><h3>Наш блог</h3></div>
{% for blog in blog_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <div class="card-body" >
                        <h3 class="card-title">{{ blog.title_post }}</h3>
                        <img src="/media/{{ blog.image_post }}" alt="Card image" class="card-image">

                    </div>
                    <div class="card p-3">
                        <a href="{% url 'blog:view' pk=blog.id %}" class="btn btn-primary">Читать</a>
                    </div>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:"4" and not forloop.last %}
            </div>
    <div class="row text-center">
        {% endif %}
{% endfor %}
</div>

{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html' %}

{%  block content %}
    <div class="row">
        <div class="6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить рассылку?</p>
                        <button type="submit" class="btn btn-success">
                            Удалить!
                        </button>
                        <a href="{% url 'index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

main/templates/main/mailing_form.html
{% extends 'main/base.html' %}
{% block content%}


<div class="container mt-5">
    <div class="row">
        <div class="col">
            <h1 class="text-center">Добавляем рассылку</h1>
        </div>
    </div>
</div>

<div class="row align-item-start p-3 border bg-light"">
    <div class="card-body">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <div class="card-body" >
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">
                {% if object %}
                    Изменить рассылку
                {% else %}
                    Создать рассылку
                {% endif %}

            </button>
        </form>
     </div>
</div>
</div>
    </div>


{% endblock %}

main/templates/main/mailinglogs.html
{% extends 'main/base.html' %}
{% block content%}


    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Страница логов</h1>
            </div>
        </div>
    </div>

{% if user.is_authenticated %}

    {% for object in object_list %}
<div class="row align-item-start p-3 border bg-light"">
    <div class="col">
        <div class="col-12 card-body">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <div class="card-body" >
                        <h4 class="card-title">Рассылка №{{ object.log_mailing }}</h4>
                        <div>Время отправки {{ object.created_time }},
                            Статус отправки - {{ object.log_status }},
                            Ответ сервера- <b>{{ object.response }}</b>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>



    {% endfor %}

{% endif %}
{% endblock %}

main/templates/main/message.html
{% extends 'main/base.html' %}
{% block content%}


<div class="container mt-5">
        <div class="row">
            <div class="col">
                <h1 class="text-center">Страница создания сообщений</h1>
            </div>
        </div>
    </div>


{% endblock %}